### PR TITLE
Fix issues with SARTSATraces

### LINKED ISSUE #70: SARTSA Traces cannot be sampled correctly
There are two problems here, and I am not sure whether they are separate or related, but I am putting them in the same issue.
Both `CircularArraySARTSATraces` as well as `ElasticArraySARTSATraces` cannot be sampled correctly using an `EpisodesSampler` or manually using the `sampleable_inds` field of the container. 

**Problem 1:**
When using the `EpisodesSampler`, it directly gives and error. This can be demonstrated with the following example code. This follows the `run` function for an agent in pushing the appropriate named tuples.
```julia
using ReinforcementLearningTrajectories, StatsBase

t = Trajectory(ElasticArraySARTSATraces(
    state = Int64 => ()),
    EpisodesSampler())

push!(t, (state = 1,)) # pre episode stage
for i in 1:3
    push!(t, (state = i+1, action = i, reward = i, terminal = false))
end
push!(t, (state = 5, action = 4, reward = 4, terminal = true)) # last step of episode
push!(t, (action = 5,)) # post episode stage

b1 = sample(t) # this sampling works

# second episode
push!(t, (state = 1,))
for i in 1:3
    push!(t, (state = i+1, action = i, reward = i, terminal = false))
end
push!(t, (state = 5, action = 4, reward = 4, terminal = true))
push!(t, (action = 5,))
b2 = sample(t) # this sample results in an error.
```
The error obtained is:
```julia
ERROR: BoundsError: attempt to access 10-element ElasticArrays.ElasticVector{Int64, Vector{Int64}} at index [8:11]
Stacktrace:
  [1] throw_boundserror(A::ElasticArrays.ElasticVector{Int64, Vector{Int64}}, I::Tuple{UnitRange{Int64}})
    @ Base ./abstractarray.jl:737
  [2] checkbounds
    @ ./abstractarray.jl:702 [inlined]
  [3] view
    @ ./subarray.jl:184 [inlined]
  [4] maybeview
    @ ./views.jl:148 [inlined]
  [5] getindex
    @ ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/traces.jl:49 [inlined]
  [6] getindex(s::ReinforcementLearningTrajectories.RelativeTrace{…}, I::UnitRange{…})
    @ ReinforcementLearningTrajectories ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/traces.jl:96
  [7] (::ReinforcementLearningTrajectories.var"#74#75"{EpisodesBuffer{…}, UnitRange{…}})(x::Symbol)
    @ ReinforcementLearningTrajectories ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/samplers.jl:282
  [8] map (repeats 2 times)
    @ ./tuple.jl:294 [inlined]
  [9] make_episode(t::EpisodesBuffer{…}, range::UnitRange{…}, names::NTuple{…})
    @ ReinforcementLearningTrajectories ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/samplers.jl:282
 [10] #76
    @ ./none:0 [inlined]
 [11] iterate
    @ ./generator.jl:47 [inlined]
 [12] collect_to!(dest::Vector{…}, itr::Base.Generator{…}, offs::Int64, st::Int64)
    @ Base ./array.jl:892
 [13] collect_to_with_first!(dest::Vector{…}, v1::Episode{…}, itr::Base.Generator{…}, st::Int64)
    @ Base ./array.jl:870
 [14] collect(itr::Base.Generator{Vector{…}, ReinforcementLearningTrajectories.var"#76#77"{…}})
    @ Base ./array.jl:844
 [15] sample(::EpisodesSampler{…}, t::EpisodesBuffer{…}, names::NTuple{…})
    @ ReinforcementLearningTrajectories ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/samplers.jl:299
 [16] sample
    @ ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/samplers.jl:278 [inlined]
 [17] sample(t::Trajectory{EpisodesBuffer{…}, EpisodesSampler{…}, InsertSampleRatioController, typeof(identity)})
    @ ReinforcementLearningTrajectories ~/.julia/packages/ReinforcementLearningTrajectories/UPp4T/src/trajectory.jl:123
 [18] top-level scope
    @ test.jl:22
Some type information was truncated. Use `show(err)` to see complete types.
```

**Problem 2:**
The `sampleable_inds` field of the trajectory container are not updated correctly as the updating progresses. If you run the following code:
```julia
t = Trajectory(ElasticArraySARTSATraces(
    state = Int64 => ()),
    EpisodesSampler())

push!(t, (state = 1,)) # pre episode stage
for i in 1:3
    push!(t, (state = i+1, action = i, reward = i, terminal = false))
end
```
and then check the `sampleable_inds` during an episode:
```
julia> t.container.sampleable_inds |> print
Bool[1, 1, 1, 0]
```
however, the index 3 of the container is not indexable and it contains only two valid trace entries.

If we look at the `sampleable_inds` after running the whole code from the top,
```
julia> t.container.sampleable_inds |> print
Bool[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0]
```
This shows that the index 6 is not sampleable, but it is the first entry of the second episode. The index 10 is shown as sampleable, but it does not exist.

### LINKED ISSUE #71: Action and state go out of sync in CircularArraySARTSATraces
When more traces are pushed into a CircularArraySARTSATraces than its capacity, then the state and action in the traces are no longer matching. This can be seen with the following example. The usage follows that of the agent in ReinforcementLearningCore
```julia
using ReinforcementLearningTrajectories

eb = EpisodesBuffer(
        CircularArraySARTSATraces(;
        capacity=3)
    )
push!(eb, (state = 1,))
for i = 1:3
    push!(eb, (state = i+1, action =i, reward = i, terminal = false))
end
```
Checking the traces:
```julia
julia> for t in eb
           println(t)
       end
(state = 1, next_state = 2, action = 1, next_action = 2, reward = 1.0f0, terminal = false)
(state = 2, next_state = 3, action = 2, next_action = 3, reward = 2.0f0, terminal = false)
```
So far it is correct, state i has action i with it. If we push some more:
```julia
for i = 4:6
    push!(eb, (state = i+1, action =i, reward = i, terminal = false))
end
``` 
```julia
julia> for t in eb
           println(t)
       end
(state = 4, next_state = 5, action = 3, next_action = 4, reward = 4.0f0, terminal = false)
(state = 5, next_state = 6, action = 4, next_action = 5, reward = 5.0f0, terminal = false)
(state = 6, next_state = 7, action = 5, next_action = 6, reward = 6.0f0, terminal = false)
```
The state i is now with action i-1, which is incorrect. It is however corrected when after the episode, a PartialNamedTuple with just an action is pushed. However, the traces will be wrong during the episode, and any algorithm that updates during an episode (in the PostActStage) will not function correctly.

### PR DESCRIPTION
**Pull request by dharux**
This fixes #70 and fixes #71.
#### Issue #70 : SARTSA Traces cannot be sampled correctly. 
The sampleable_inds field of the episodes buffer containing a SARTSATrace (CircularArraySARTSATraces or ElasticArraySARTSATraces) was not correctly keeping track of which indices are sampleable. In a SARTSATraces, information from 3 steps are required to complete a single trace. The initial step of the episode in which only the state is pushed. The next step in which the action and next_state are pushed. The following step in which the next_action is pushed. Now, there is one sampleable index, but two unsampleable ones. Thus, the last two indices in the trace are typically unsampleable during the episode. This change was made to the function `Base.push!(eb::EpisodesBuffer, xs::NamedTuple)` in episodes.jl. 

#### Issue #71 : Action and state go out of sync in CircularArraySARTSATraces
When more traces are pushed into the Traces than its capacity, the state does not match the appropriate action. To fix this, the capacity of the state trace should be one more than that of the action trace. The capacity of all traces are incremented by 1 so that the Traces can hold `capacity` amount of full traces. 

##

The tests were also modified to check that it works correctly with the following usage:
1. Push first state at the start of the episode (`PreEpisodeStage` in RL.jl)
2. Push state, action, reward, terminal during the episode (`PostActStage`)
3. Push action after the episode ends in a PartialNamedTuple (`PostEpisodeStage`)

This is the behaviour of the agent from RLCore.jl and all trajectories should work well with that. The `CircularArraySARTSATraces` are a bit restrictive with regards to usage and cannot be used very differently than the typical usage above. I have not been able to make it work while represented next_action and working with all general usage.

The `CircularArrarySARTSATraces` do not currently work with `CircularPrioritizedTraces` as these add additional keys like `keys` and `priorities` which are updated outside of the Traces. Some changes need to be made with `CircularPrioritizedTraces` to make it work with `CircularArrarySARTSATraces` also. Thus, there are 2 errors during the testing involving `CircularPrioritizedTraces`.

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
@dharux Thank you for the PR. I've updated the main branch to eliminate unrelated test failures. Would you able to resolve the remaining test errors (in `CircularPrioritizedTraces`)?

**Comment by dharux** [comment]
I could take a shot at it. It might require completely rewriting how tuples are pushed into a `CircularPrioritizedTraces` and how it is sampled for the case when it contains a `CircularArraySARTSATraces`.

**Comment by jeremiahpslewis** [comment]
@HenriDeh any tips or pointers for @dharux

**Comment by jeremiahpslewis** [comment]
@dharux Thanks, looks good to me, I’ll let @HenriDeh do a final check.

**Comment by dharux** [comment]
Needed some final fixes. Everything should be working now!

**Review by HenriDeh — APPROVED** [review]
Thanks for taking the time. Sampleable indices are not very intuitive, I hope this didn't give you headaches.

**Pull request merged**
