### PR TITLE
Fix interaction between CircularPrioritizedTraces and NStepBatchSampler

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
- Fixes issue where dispatch on Circular Trajectories was not working for certain samplers, this I believe has been causing CI for https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/921 to fail as type dispatch fails to match :priority and :key keys

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
~@HenriDeh now running into an issue where `sampleable_inds` is `length(x) + 2` of the trace length, but it should be `length(x) + 1)`, any ideas why?~ Capacity for EpisodeBuffer wasn't correctly set.

**Comment by jeremiahpslewis** [comment]
@HenriDeh Merged this as it only adds tests and fixes functionality.

**Comment by HenriDeh** [comment]
Hi @jeremiahpslewis, sorry I was on vacations. I'll catch up when I resume work on Monday.

**Comment by jeremiahpslewis** [comment]
@HenriDeh I figured as much. Hope you had a great trip!

**Pull request merged**
